package com.google.android.gms.nearby;

import com.google.android.gms.common.Feature;

public final class zza {
    public static final Feature zzA;
    public static final Feature zzB;
    public static final Feature zzC;
    public static final Feature zzD;
    public static final Feature zzE;
    public static final Feature zzF;
    public static final Feature zzG;
    public static final Feature zzH;
    public static final Feature zzI;
    public static final Feature zzJ;
    public static final Feature zzK;
    public static final Feature zzL;
    public static final Feature zzM;
    public static final Feature zzN;
    public static final Feature zzO;
    public static final Feature zzP;
    public static final Feature zzQ;
    public static final Feature[] zzR;
    public static final Feature zza;
    public static final Feature zzb;
    public static final Feature zzc;
    public static final Feature zzd;
    public static final Feature zze;
    public static final Feature zzf;
    public static final Feature zzg;
    public static final Feature zzh;
    public static final Feature zzi;
    public static final Feature zzj;
    public static final Feature zzk;
    public static final Feature zzl;
    public static final Feature zzm;
    public static final Feature zzn;
    public static final Feature zzo;
    public static final Feature zzp;
    public static final Feature zzq;
    public static final Feature zzr;
    public static final Feature zzs;
    public static final Feature zzt;
    public static final Feature zzu;
    public static final Feature zzv;
    public static final Feature zzw;
    public static final Feature zzx;
    public static final Feature zzy;
    public static final Feature zzz;

    static {
        Feature feature = new Feature("nearby_sharing", 35);
        zza = feature;
        Feature feature2 = new Feature("nearby_sharing_allow_permission_auto", 1);
        zzb = feature2;
        Feature feature3 = new Feature("nearby_sharing_get_phone_numbers", 1);
        zzc = feature3;
        Feature feature4 = new Feature("nearby_sharing_ignore_consent", 2);
        zzd = feature4;
        Feature feature5 = new Feature("nearby_sharing_phonesky", 6);
        zze = feature5;
        Feature feature6 = new Feature("nearby_connections", 3);
        zzf = feature6;
        Feature feature7 = new Feature("nearby_connections_v2", 1);
        zzg = feature7;
        Feature feature8 = new Feature("nearby_exposure_notification", 3);
        zzh = feature8;
        Feature feature9 = new Feature("nearby_exposure_notification_1p", 1);
        zzi = feature9;
        Feature feature10 = new Feature("nearby_exposure_notification_get_version", 1);
        zzj = feature10;
        Feature feature11 = new Feature("nearby_exposure_notification_get_calibration_confidence", 1);
        zzk = feature11;
        Feature feature12 = new Feature("nearby_exposure_notification_get_day_summaries", 1);
        zzl = feature12;
        Feature feature13 = new Feature("nearby_exposure_notification_get_status", 1);
        zzm = feature13;
        Feature feature14 = feature13;
        Feature feature15 = new Feature("nearby_exposure_notification_diagnosis_keys_data_mapping", 1);
        zzn = feature15;
        Feature feature16 = feature15;
        Feature feature17 = new Feature("nearby_exposure_notification_diagnosis_key_file_supplier", 1);
        zzo = feature17;
        Feature feature18 = feature17;
        Feature feature19 = new Feature("nearby_exposure_notification_package_configuration", 1);
        zzp = feature19;
        Feature feature20 = feature19;
        Feature feature21 = new Feature("nearby_exposure_notification_preauthorize_key_release", 1);
        zzq = feature21;
        Feature feature22 = feature21;
        Feature feature23 = new Feature("nearby_exposure_notification_preauthorize_key_release_for_self_report", 1);
        zzr = feature23;
        Feature feature24 = new Feature("nearby_fast_pair", 2);
        zzs = feature24;
        Feature feature25 = feature24;
        Feature feature26 = new Feature("nearby_fast_pair_sass", 4);
        zzt = feature26;
        Feature feature27 = new Feature("nearby_fast_pair_wear_os", 3);
        zzu = feature27;
        Feature feature28 = new Feature("nearby_fast_pair_wear_peripheral", 1);
        zzv = feature28;
        Feature feature29 = new Feature("nearby_fast_pair_wear_peripheral_notify_disable", 1);
        zzw = feature29;
        Feature feature30 = feature11;
        Feature feature31 = new Feature("nearby_presence", 5);
        zzx = feature31;
        Feature feature32 = new Feature("nearby_presence_reset", 1);
        zzy = feature32;
        Feature feature33 = new Feature("nearby_presence_sync", 1);
        zzz = feature33;
        Feature feature34 = new Feature("nearby_connections_get_local_endpoint_id", 1);
        zzA = feature34;
        Feature feature35 = new Feature("nearby_connections_register_device_provider", 1);
        zzB = feature35;
        Feature feature36 = new Feature("nearby_connections_update_advertising_options", 1);
        zzC = feature36;
        Feature feature37 = new Feature("nearby_connections_update_discovery_options", 1);
        zzD = feature37;
        Feature feature38 = new Feature("nearby_connections_setting", 1);
        zzE = feature38;
        Feature feature39 = feature30;
        Feature feature40 = new Feature("nearby_sharing_everyone_mode", 2);
        zzF = feature40;
        Feature feature41 = new Feature("nearby_sharing_toggle_fast_init_notification", 1);
        zzG = feature41;
        Feature feature42 = feature41;
        Feature feature43 = new Feature("nearby_sharing_batch_contacts_editing_request", 1);
        zzH = feature43;
        Feature feature44 = feature27;
        Feature feature45 = feature39;
        Feature feature46 = new Feature("nearby_uwb", 3);
        zzI = feature46;
        Feature feature47 = new Feature("nearby_uwb_add_controlee", 2);
        zzJ = feature47;
        Feature feature48 = feature47;
        Feature feature49 = new Feature("nearby_uwb_remove_controlee", 2);
        zzK = feature49;
        Feature feature50 = feature49;
        Feature feature51 = new Feature("nearby_sharing_get_intent", 2);
        zzL = feature51;
        Feature feature52 = feature43;
        Feature feature53 = feature45;
        Feature feature54 = new Feature("nearby_sharing_get_share_targets", 1);
        zzM = feature54;
        Feature feature55 = new Feature("nearby_sharing_sync", 2);
        zzN = feature55;
        Feature feature56 = feature51;
        Feature feature57 = new Feature("nearby_sharing_get_actions", 5);
        zzO = feature57;
        Feature feature58 = new Feature("nearby_sharing_opt_in_by_remote_copy", 1);
        zzP = feature58;
        Feature feature59 = new Feature("nearby_sharing_get_opt_in_status", 1);
        zzQ = feature59;
        zzR = new Feature[]{feature, feature2, feature3, feature4, feature5, feature6, feature7, feature8, feature9, feature10, feature53, feature12, feature14, feature16, feature18, feature20, feature22, feature23, feature25, feature26, feature44, feature28, feature29, feature31, feature32, feature33, feature34, feature35, feature36, feature37, feature38, feature40, feature42, feature52, feature46, feature48, feature50, feature56, feature54, feature55, feature57, feature58, feature59};
    }
}
