package p069e3;

import p069e3.C4528a;

/* renamed from: e3.d */
public final class C4539d {

    /* renamed from: a */
    public static final C4528a.C4532d f15655a = new C4528a.C4532d("FORCE_DARK", "FORCE_DARK");

    /* renamed from: b */
    public static final C4528a.C4532d f15656b = new C4528a.C4532d("FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR");

    static {
        new C4528a.C4530b("VISUAL_STATE_CALLBACK", "VISUAL_STATE_CALLBACK");
        new C4528a.C4530b("OFF_SCREEN_PRERASTER", "OFF_SCREEN_PRERASTER");
        new C4528a.C4533e("SAFE_BROWSING_ENABLE", "SAFE_BROWSING_ENABLE");
        new C4528a.C4531c("DISABLED_ACTION_MODE_MENU_ITEMS", "DISABLED_ACTION_MODE_MENU_ITEMS");
        new C4528a.C4534f("START_SAFE_BROWSING", "START_SAFE_BROWSING");
        new C4528a.C4534f("SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_WHITELIST");
        new C4528a.C4534f("SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_ALLOWLIST");
        new C4528a.C4534f("SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_WHITELIST");
        new C4528a.C4534f("SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_ALLOWLIST");
        new C4528a.C4534f("SAFE_BROWSING_PRIVACY_POLICY_URL", "SAFE_BROWSING_PRIVACY_POLICY_URL");
        new C4528a.C4531c("SERVICE_WORKER_BASIC_USAGE", "SERVICE_WORKER_BASIC_USAGE");
        new C4528a.C4531c("SERVICE_WORKER_CACHE_MODE", "SERVICE_WORKER_CACHE_MODE");
        new C4528a.C4531c("SERVICE_WORKER_CONTENT_ACCESS", "SERVICE_WORKER_CONTENT_ACCESS");
        new C4528a.C4531c("SERVICE_WORKER_FILE_ACCESS", "SERVICE_WORKER_FILE_ACCESS");
        new C4528a.C4531c("SERVICE_WORKER_BLOCK_NETWORK_LOADS", "SERVICE_WORKER_BLOCK_NETWORK_LOADS");
        new C4528a.C4531c("SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST");
        new C4528a.C4530b("RECEIVE_WEB_RESOURCE_ERROR", "RECEIVE_WEB_RESOURCE_ERROR");
        new C4528a.C4530b("RECEIVE_HTTP_ERROR", "RECEIVE_HTTP_ERROR");
        new C4528a.C4531c("SHOULD_OVERRIDE_WITH_REDIRECTS", "SHOULD_OVERRIDE_WITH_REDIRECTS");
        new C4528a.C4534f("SAFE_BROWSING_HIT", "SAFE_BROWSING_HIT");
        new C4528a.C4531c("WEB_RESOURCE_REQUEST_IS_REDIRECT", "WEB_RESOURCE_REQUEST_IS_REDIRECT");
        new C4528a.C4530b("WEB_RESOURCE_ERROR_GET_DESCRIPTION", "WEB_RESOURCE_ERROR_GET_DESCRIPTION");
        new C4528a.C4530b("WEB_RESOURCE_ERROR_GET_CODE", "WEB_RESOURCE_ERROR_GET_CODE");
        new C4528a.C4534f("SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY");
        new C4528a.C4534f("SAFE_BROWSING_RESPONSE_PROCEED", "SAFE_BROWSING_RESPONSE_PROCEED");
        new C4528a.C4534f("SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL");
        new C4528a.C4530b("WEB_MESSAGE_PORT_POST_MESSAGE", "WEB_MESSAGE_PORT_POST_MESSAGE");
        new C4528a.C4530b("WEB_MESSAGE_PORT_CLOSE", "WEB_MESSAGE_PORT_CLOSE");
        new C4528a.C4530b("WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK");
        new C4528a.C4530b("CREATE_WEB_MESSAGE_CHANNEL", "CREATE_WEB_MESSAGE_CHANNEL");
        new C4528a.C4530b("POST_WEB_MESSAGE", "POST_WEB_MESSAGE");
        new C4528a.C4530b("WEB_MESSAGE_CALLBACK_ON_MESSAGE", "WEB_MESSAGE_CALLBACK_ON_MESSAGE");
        new C4528a.C4533e("GET_WEB_VIEW_CLIENT", "GET_WEB_VIEW_CLIENT");
        new C4528a.C4533e("GET_WEB_CHROME_CLIENT", "GET_WEB_CHROME_CLIENT");
        new C4528a.C4536h("GET_WEB_VIEW_RENDERER", "GET_WEB_VIEW_RENDERER");
        new C4528a.C4536h("WEB_VIEW_RENDERER_TERMINATE", "WEB_VIEW_RENDERER_TERMINATE");
        new C4528a.C4535g();
        new C4528a.C4536h("WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE");
        new C4528a.C4532d("PROXY_OVERRIDE", "PROXY_OVERRIDE:3");
        new C4528a.C4532d("SUPPRESS_ERROR_PAGE", "SUPPRESS_ERROR_PAGE");
        new C4528a.C4532d("MULTI_PROCESS", "MULTI_PROCESS_QUERY");
        new C4528a.C4532d("ALGORITHMIC_DARKENING", "ALGORITHMIC_DARKENING");
        new C4528a.C4532d("WEB_MESSAGE_LISTENER", "WEB_MESSAGE_LISTENER");
        new C4528a.C4532d("DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1");
        new C4528a.C4532d("PROXY_OVERRIDE_REVERSE_BYPASS", "PROXY_OVERRIDE_REVERSE_BYPASS");
        new C4528a.C4532d("GET_VARIATIONS_HEADER", "GET_VARIATIONS_HEADER");
        new C4528a.C4532d("REQUESTED_WITH_HEADER_CONTROL", "REQUESTED_WITH_HEADER_CONTROL");
        new C4528a.C4532d("ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY");
    }
}
